CREATE DATABASE Asign_04

USE Asign_04

CREATE TABLE NguoiCTN(
MaNCTN varchar(10) PRIMARY KEY,
TenNCTN nvarchar(20),
)

INSERT INTO NguoiCTN VALUES (456,N' hùng')
INSERT INTO NguoiCTN VALUES (457,N' anh')
INSERT INTO NguoiCTN VALUES (458,N' mai')


CREATE TABLE PhieuSP(
MaSP varchar(10) PRIMARY KEY,
MaNCTN varchar(10),
NgaySX varchar(10),
CONSTRAINT FK_Ma FOREIGN KEY (MaNCTN) REFERENCES  NguoiCTN(MaNCTN)
)
INSERT INTO PhieuSP VALUES (203,456,'09/25/2020')
INSERT INTO PhieuSP VALUES (204,457,'10/15/2015')
INSERT INTO PhieuSP VALUES (205,458,'07/25/2010')
INSERT INTO PhieuSP VALUES (206,456,'05/20/2019')
INSERT INTO PhieuSP VALUES (207,456,'05/20/2019')


CREATE TABLE PhieuSPCT(
MaSP varchar(10) PRIMARY KEY,
TenSP nvarchar(100),
LoaiSP varchar(10)
)
ALTER TABLE PhieuSP ADD CONSTRAINT FK_MaSP FOREIGN KEY (MaSP) REFERENCES PhieuSP(MaSP)
GO
INSERT INTO PhieuSPCT VALUES (203,N'Máy tính','Z1000')
INSERT INTO PhieuSPCT VALUES (204,N'Chăn','Z2000')
INSERT INTO PhieuSPCT VALUES (205,N'La bàn','Z3000')
INSERT INTO PhieuSPCT VALUES (206,N'điện thoại','Z4000')
INSERT INTO PhieuSPCT VALUES (207,N'điện thoại','A4000')
GO
--4a
SELECT LoaiSP FROM PhieuSPCT
--4b
SELECT TenSP FROM PhieuSPCT
--4c
SELECT TenNCTN FROM NguoiCTN
--5a
SELECT LoaiSP FROM PhieuSPCT
ORDER BY LoaiSP ASC
--5b
SELECT TenNCTN FROM NguoiCTN
ORDER BY TenNCTN ASC
--5c
SELECT TenSP,LoaiSP FROM PhieuSPCT
WHERE LoaiSP = 'A4000'
--5d
SELECT a.TenNCTN,c.TenSP FROM NguoiCTN AS a JOIN PhieuSP AS b ON a.MaNCTN = b.MaNCTN
										 JOIN PhieuSPCT AS c ON c.MaSP = b.MaSP
WHERE a.TenNCTN = N' hùng'
GROUP BY a.TenNCTN,c.TenSP
--6a
SELECT MaSP,LoaiSP FROM PhieuSPCT
--6c
SELECT * FROM PhieuSPCT 
--6d
SELECT TenNCTN,TenSP,LoaiSP FROM NguoiCTN AS a JOIN PhieuSP AS b ON a.MaNCTN = b.MaNCTN
										 JOIN PhieuSPCT AS c ON c.MaSP = b.MaSP
--7a										 
ALTER TABLE PhieuSP ADD CONSTRAINT Phieu_ CHECK (NgaySX <= getdate());
--7b
select * from INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
--8a
CREATE INDEX ID_NguoiCTN ON NguoiCTN(TenNCTN)
--8b
CREATE VIEW veiw_sanpham AS
SELECT c.MaSP,b.NgaySX,c.LoaiSP
FROM NguoiCTN AS a JOIN PhieuSP AS b ON a.MaNCTN = b.MaNCTN
				JOIN PhieuSPCT AS c ON c.MaSP = b.MaSP

CREATE VIEW veiw_sanpham_nctn AS
SELECT c.MaSP,b.NgaySX,a.TenNCTN
FROM NguoiCTN AS a JOIN PhieuSP AS b ON a.MaNCTN = b.MaNCTN
				JOIN PhieuSPCT AS c ON c.MaSP = b.MaSP

CREATE VIEW veiw_top_sanpham AS
SELECT top(2)b.MaSP,c.LoaiSP,b.NgaySX 
FROM NguoiCTN AS a JOIN PhieuSP AS b ON a.MaNCTN = b.MaNCTN
				JOIN PhieuSPCT AS c ON c.MaSP = b.MaSP
select * From veiw_top_sanpham 